name: elas_promocoes
description: Catálogo online de promoções da Ela Promoções.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.0.2
  firebase_core: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  envied_generator: ^0.2.3
  build_runner: ^2.3.2

flutter:
  uses-material-design: true