name: elas_promocoes
description: Catálogo online de promoções da Ela Promoções.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  currency_text_input_formatter: ^2.1.8
  image_picker: ^0.8.6
  flutter_hooks: ^0.18.5+1
  cloud_firestore: ^4.0.4
  currency_formatter: ^2.0.0
  firebase_storage: ^11.0.4
  url_launcher: ^6.1.6
  share_plus: ^6.2.0
  hooks_riverpod: ^2.1.1
  go_router: ^5.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.14

flutter:
  uses-material-design: true
  assets:
    - assets/